### ISSUE TITLE
Link to the firefox store not working?

### ISSUE THREAD

**Issue by Godiesc** [datastring/firefox-whatsapp-in-sidebar#1]
hi,
you have this extension available in the store of Firefox? the links from the main page don't work.

**Comment by semanticdata** [comment]
Hello,

Apologies, the listing was hidden due to a DMCA takedown notice from Meta. It has been resolved, and you can find the extension [here](https://addons.mozilla.org/en-US/firefox/addon/whatsapp-within-sidebar/). Thank you for reaching out.

**Comment by Godiesc** [comment]
thanks, maybe you are using the icon with copyright jeje it's better to use an edited image, I'm starting to create an extension and I would like to know whats was the problem with your extension to don't get the same problem.

**Comment by semanticdata** [comment]
Happy to help.

What happened was, Appdetex, on behalf of Meta Platforms, Inc. sent a DMCA notice about my addon to Mozilla. They immediately took it down and marked it as "disabled by Mozilla". This removed/blocked all my abilities to modify the addon listing.

The problem begins and ends with Appdetex, who seems to send DMCA notices automatically to any new addon published using the "WhatsApp" branding. If that happens, you'll be required to send a counter notification to <dmcanotice@mozilla.com>.

You should refer to Mozilla's DMCA and Trademark policy page at <https://www.mozilla.org/about/legal/report-infringement> for the requirements for a valid counter notification and some more information. 

You can find the WhatsApp brand guidelines [here](https://about.meta.com/brand/resources/whatsapp/whatsapp-brand).

**Comment by Godiesc** [comment]
wooow, thanks for the info ❤, I made an extension of instagram, it's the same company that whatsapp, maybe I will have the same problem.
